// list all the flags here

import 'package:flags/model/flag.dart';

final flags = [
  FlagObject(name: "Afghanistan", countryCode: "AF"),
  FlagObject(name: "Albania", countryCode: "AL"),
  FlagObject(name: "Algeria", countryCode: "DZ"),
  FlagObject(name: "American Samoa", countryCode: "AS"),
  FlagObject(name: "Andorra", countryCode: "AD"),
  FlagObject(name: "Angola", countryCode: "AO"),
  FlagObject(name: "Anguilla", countryCode: "AI"),
  FlagObject(name: "Antarctica", countryCode: "AQ"),
  FlagObject(name: "Antigua and Barbuda", countryCode: "AG"),
  FlagObject(name: "Argentina", countryCode: "AR"),
  FlagObject(name: "Armenia", countryCode: "AM"),
  FlagObject(name: "Aruba", countryCode: "AW"),
  FlagObject(name: "Australia", countryCode: "AU"),
  FlagObject(name: "Austria", countryCode: "AT"),
  FlagObject(name: "Azerbaijan", countryCode: "AZ"),
  FlagObject(name: "Bahamas (the)", countryCode: "BS"),
  FlagObject(name: "Bahrain", countryCode: "BH"),
  FlagObject(name: "Bangladesh", countryCode: "BD"),
  FlagObject(name: "Barbados", countryCode: "BB"),
  FlagObject(name: "Belarus", countryCode: "BY"),
  FlagObject(name: "Belgium", countryCode: "BE"),
  FlagObject(name: "Belize", countryCode: "BZ"),
  FlagObject(name: "Benin", countryCode: "BJ"),
  FlagObject(name: "Bermuda", countryCode: "BM"),
  FlagObject(name: "Bhutan", countryCode: "BT"),
  FlagObject(name: "Bolivia (Plurinational State of)", countryCode: "BO"),
  FlagObject(name: "Bonaire, Sint Eustatius and Saba", countryCode: "BQ"),
  FlagObject(name: "Bosnia and Herzegovina", countryCode: "BA"),
  FlagObject(name: "Botswana", countryCode: "BW"),
  FlagObject(name: "Bouvet Island", countryCode: "BV"),
  FlagObject(name: "Brazil", countryCode: "BR"),
  FlagObject(name: "British Indian Ocean Territory (the)", countryCode: "IO"),
  FlagObject(name: "Brunei Darussalam", countryCode: "BN"),
  FlagObject(name: "Bulgaria", countryCode: "BG"),
  FlagObject(name: "Burkina Faso", countryCode: "BF"),
  FlagObject(name: "Burundi", countryCode: "BI"),
  FlagObject(name: "Cabo Verde", countryCode: "CV"),
  FlagObject(name: "Cambodia", countryCode: "KH"),
  FlagObject(name: "Cameroon", countryCode: "CM"),
  FlagObject(name: "Canada", countryCode: "CA"),
  FlagObject(name: "Cayman Islands (the)", countryCode: "KY"),
  FlagObject(name: "Central African Republic (the)", countryCode: "CF"),
  FlagObject(name: "Chad", countryCode: "TD"),
  FlagObject(name: "Chile", countryCode: "CL"),
  FlagObject(name: "China", countryCode: "CN"),
  FlagObject(name: "Christmas Island", countryCode: "CX"),
  FlagObject(name: "Cocos (Keeling) Islands (the)", countryCode: "CC"),
  FlagObject(name: "Colombia", countryCode: "CO"),
  FlagObject(name: "Comoros (the)", countryCode: "KM"),
  FlagObject(name: "Congo (the Democratic Republic of the)", countryCode: "CD"),
  FlagObject(name: "Congo (the)", countryCode: "CG"),
  FlagObject(name: "Cook Islands (the)", countryCode: "CK"),
  FlagObject(name: "Costa Rica", countryCode: "CR"),
  FlagObject(name: "Croatia", countryCode: "HR"),
  FlagObject(name: "Cuba", countryCode: "CU"),
  FlagObject(name: "Curaçao", countryCode: "CW"),
  FlagObject(name: "Cyprus", countryCode: "CY"),
  FlagObject(name: "Czechia", countryCode: "CZ"),
  FlagObject(name: "Côte d'Ivoire", countryCode: "CI"),
  FlagObject(name: "Denmark", countryCode: "DK"),
  FlagObject(name: "Djibouti", countryCode: "DJ"),
  FlagObject(name: "Dominica", countryCode: "DM"),
  FlagObject(name: "Dominican Republic (the)", countryCode: "DO"),
  FlagObject(name: "Ecuador", countryCode: "EC"),
  FlagObject(name: "Egypt", countryCode: "EG"),
  FlagObject(name: "El Salvador", countryCode: "SV"),
  FlagObject(name: "Equatorial Guinea", countryCode: "GQ"),
  FlagObject(name: "Eritrea", countryCode: "ER"),
  FlagObject(name: "Estonia", countryCode: "EE"),
  FlagObject(name: "Eswatini", countryCode: "SZ"),
  FlagObject(name: "Ethiopia", countryCode: "ET"),
  FlagObject(name: "Falkland Islands (the) [Malvinas]", countryCode: "FK"),
  FlagObject(name: "Faroe Islands (the)", countryCode: "FO"),
  FlagObject(name: "Fiji", countryCode: "FJ"),
  FlagObject(name: "Finland", countryCode: "FI"),
  FlagObject(name: "France", countryCode: "FR"),
  FlagObject(name: "French Guiana", countryCode: "GF"),
  FlagObject(name: "French Polynesia", countryCode: "PF"),
  FlagObject(name: "French Southern Territories (the)", countryCode: "TF"),
  FlagObject(name: "Gabon", countryCode: "GA"),
  FlagObject(name: "Gambia (the)", countryCode: "GM"),
  FlagObject(name: "Georgia", countryCode: "GE"),
  FlagObject(name: "Germany", countryCode: "DE"),
  FlagObject(name: "Ghana", countryCode: "GH"),
  FlagObject(name: "Gibraltar", countryCode: "GI"),
  FlagObject(name: "Greece", countryCode: "GR"),
  FlagObject(name: "Greenland", countryCode: "GL"),
  FlagObject(name: "Grenada", countryCode: "GD"),
  FlagObject(name: "Guadeloupe", countryCode: "GP"),
  FlagObject(name: "Guam", countryCode: "GU"),
  FlagObject(name: "Guatemala", countryCode: "GT"),
  FlagObject(name: "Guernsey", countryCode: "GG"),
  FlagObject(name: "Guinea", countryCode: "GN"),
  FlagObject(name: "Guinea-Bissau", countryCode: "GW"),
  FlagObject(name: "Guyana", countryCode: "GY"),
  FlagObject(name: "Haiti", countryCode: "HT"),
  FlagObject(name: "Heard Island and McDonald Islands", countryCode: "HM"),
  FlagObject(name: "Holy See (the)", countryCode: "VA"),
  FlagObject(name: "Honduras", countryCode: "HN"),
  FlagObject(name: "Hong Kong", countryCode: "HK"),
  FlagObject(name: "Hungary", countryCode: "HU"),
  FlagObject(name: "Iceland", countryCode: "IS"),
  FlagObject(name: "India", countryCode: "IN"),
  FlagObject(name: "Indonesia", countryCode: "ID"),
  FlagObject(name: "Iran (Islamic Republic of)", countryCode: "IR"),
  FlagObject(name: "Iraq", countryCode: "IQ"),
  FlagObject(name: "Ireland", countryCode: "IE"),
  FlagObject(name: "Isle of Man", countryCode: "IM"),
  FlagObject(name: "Israel", countryCode: "IL"),
  FlagObject(name: "Italy", countryCode: "IT"),
  FlagObject(name: "Jamaica", countryCode: "JM"),
  FlagObject(name: "Japan", countryCode: "JP"),
  FlagObject(name: "Jersey", countryCode: "JE"),
  FlagObject(name: "Jordan", countryCode: "JO"),
  FlagObject(name: "Kazakhstan", countryCode: "KZ"),
  FlagObject(name: "Kenya", countryCode: "KE"),
  FlagObject(name: "Kiribati", countryCode: "KI"),
  FlagObject(
      name: "Korea (the Democratic People's Republic of)", countryCode: "KP"),
  FlagObject(name: "Korea (the Republic of)", countryCode: "KR"),
  FlagObject(name: "Kuwait", countryCode: "KW"),
  FlagObject(name: "Kyrgyzstan", countryCode: "KG"),
  FlagObject(name: "Lao People's Democratic Republic (the)", countryCode: "LA"),
  FlagObject(name: "Latvia", countryCode: "LV"),
  FlagObject(name: "Lebanon", countryCode: "LB"),
  FlagObject(name: "Lesotho", countryCode: "LS"),
  FlagObject(name: "Liberia", countryCode: "LR"),
  FlagObject(name: "Libya", countryCode: "LY"),
  FlagObject(name: "Liechtenstein", countryCode: "LI"),
  FlagObject(name: "Lithuania", countryCode: "LT"),
  FlagObject(name: "Luxembourg", countryCode: "LU"),
  FlagObject(name: "Macao", countryCode: "MO"),
  FlagObject(name: "Madagascar", countryCode: "MG"),
  FlagObject(name: "Malawi", countryCode: "MW"),
  FlagObject(name: "Malaysia", countryCode: "MY"),
  FlagObject(name: "Maldives", countryCode: "MV"),
  FlagObject(name: "Mali", countryCode: "ML"),
  FlagObject(name: "Malta", countryCode: "MT"),
  FlagObject(name: "Marshall Islands (the)", countryCode: "MH"),
  FlagObject(name: "Martinique", countryCode: "MQ"),
  FlagObject(name: "Mauritania", countryCode: "MR"),
  FlagObject(name: "Mauritius", countryCode: "MU"),
  FlagObject(name: "Mayotte", countryCode: "YT"),
  FlagObject(name: "Mexico", countryCode: "MX"),
  FlagObject(name: "Micronesia (Federated States of)", countryCode: "FM"),
  FlagObject(name: "Moldova (the Republic of)", countryCode: "MD"),
  FlagObject(name: "Monaco", countryCode: "MC"),
  FlagObject(name: "Mongolia", countryCode: "MN"),
  FlagObject(name: "Montenegro", countryCode: "ME"),
  FlagObject(name: "Montserrat", countryCode: "MS"),
  FlagObject(name: "Morocco", countryCode: "MA"),
  FlagObject(name: "Mozambique", countryCode: "MZ"),
  FlagObject(name: "Myanmar", countryCode: "MM"),
  FlagObject(name: "Namibia", countryCode: "NA"),
  FlagObject(name: "Nauru", countryCode: "NR"),
  FlagObject(name: "Nepal", countryCode: "NP"),
  FlagObject(name: "Netherlands (the)", countryCode: "NL"),
  FlagObject(name: "New Caledonia", countryCode: "NC"),
  FlagObject(name: "New Zealand", countryCode: "NZ"),
  FlagObject(name: "Nicaragua", countryCode: "NI"),
  FlagObject(name: "Niger (the)", countryCode: "NE"),
  FlagObject(name: "Nigeria", countryCode: "NG"),
  FlagObject(name: "Niue", countryCode: "NU"),
  FlagObject(name: "Norfolk Island", countryCode: "NF"),
  FlagObject(name: "Northern Mariana Islands (the)", countryCode: "MP"),
  FlagObject(name: "Norway", countryCode: "NO"),
  FlagObject(name: "Oman", countryCode: "OM"),
  FlagObject(name: "Pakistan", countryCode: "PK"),
  FlagObject(name: "Palau", countryCode: "PW"),
  FlagObject(name: "Palestine, State of", countryCode: "PS"),
  FlagObject(name: "Panama", countryCode: "PA"),
  FlagObject(name: "Papua New Guinea", countryCode: "PG"),
  FlagObject(name: "Paraguay", countryCode: "PY"),
  FlagObject(name: "Peru", countryCode: "PE"),
  FlagObject(name: "Philippines (the)", countryCode: "PH"),
  FlagObject(name: "Pitcairn", countryCode: "PN"),
  FlagObject(name: "Poland", countryCode: "PL"),
  FlagObject(name: "Portugal", countryCode: "PT"),
  FlagObject(name: "Puerto Rico", countryCode: "PR"),
  FlagObject(name: "Qatar", countryCode: "QA"),
  FlagObject(name: "Republic of North Macedonia", countryCode: "MK"),
  FlagObject(name: "Romania", countryCode: "RO"),
  FlagObject(name: "Russian Federation (the)", countryCode: "RU"),
  FlagObject(name: "Rwanda", countryCode: "RW"),
  FlagObject(name: "Réunion", countryCode: "RE"),
  FlagObject(name: "Saint Barthélemy", countryCode: "BL"),
  FlagObject(
      name: "Saint Helena, Ascension and Tristan da Cunha", countryCode: "SH"),
  FlagObject(name: "Saint Kitts and Nevis", countryCode: "KN"),
  FlagObject(name: "Saint Lucia", countryCode: "LC"),
  FlagObject(name: "Saint Martin (French part)", countryCode: "MF"),
  FlagObject(name: "Saint Pierre and Miquelon", countryCode: "PM"),
  FlagObject(name: "Saint Vincent and the Grenadines", countryCode: "VC"),
  FlagObject(name: "Samoa", countryCode: "WS"),
  FlagObject(name: "San Marino", countryCode: "SM"),
  FlagObject(name: "Sao Tome and Principe", countryCode: "ST"),
  FlagObject(name: "Saudi Arabia", countryCode: "SA"),
  FlagObject(name: "Senegal", countryCode: "SN"),
  FlagObject(name: "Serbia", countryCode: "RS"),
  FlagObject(name: "Seychelles", countryCode: "SC"),
  FlagObject(name: "Sierra Leone", countryCode: "SL"),
  FlagObject(name: "Singapore", countryCode: "SG"),
  FlagObject(name: "Sint Maarten (Dutch part)", countryCode: "SX"),
  FlagObject(name: "Slovakia", countryCode: "SK"),
  FlagObject(name: "Slovenia", countryCode: "SI"),
  FlagObject(name: "Solomon Islands", countryCode: "SB"),
  FlagObject(name: "Somalia", countryCode: "SO"),
  FlagObject(name: "South Africa", countryCode: "ZA"),
  FlagObject(
      name: "South Georgia and the South Sandwich Islands", countryCode: "GS"),
  FlagObject(name: "South Sudan", countryCode: "SS"),
  FlagObject(name: "Spain", countryCode: "ES"),
  FlagObject(name: "Sri Lanka", countryCode: "LK"),
  FlagObject(name: "Sudan (the)", countryCode: "SD"),
  FlagObject(name: "Suriname", countryCode: "SR"),
  FlagObject(name: "Svalbard and Jan Mayen", countryCode: "SJ"),
  FlagObject(name: "Sweden", countryCode: "SE"),
  FlagObject(name: "Switzerland", countryCode: "CH"),
  FlagObject(name: "Syrian Arab Republic", countryCode: "SY"),
  FlagObject(name: "Taiwan (Province of China)", countryCode: "TW"),
  FlagObject(name: "Tajikistan", countryCode: "TJ"),
  FlagObject(name: "Tanzania, United Republic of", countryCode: "TZ"),
  FlagObject(name: "Thailand", countryCode: "TH"),
  FlagObject(name: "Timor-Leste", countryCode: "TL"),
  FlagObject(name: "Togo", countryCode: "TG"),
  FlagObject(name: "Tokelau", countryCode: "TK"),
  FlagObject(name: "Tonga", countryCode: "TO"),
  FlagObject(name: "Trinidad and Tobago", countryCode: "TT"),
  FlagObject(name: "Tunisia", countryCode: "TN"),
  FlagObject(name: "Turkey", countryCode: "TR"),
  FlagObject(name: "Turkmenistan", countryCode: "TM"),
  FlagObject(name: "Turks and Caicos Islands (the)", countryCode: "TC"),
  FlagObject(name: "Tuvalu", countryCode: "TV"),
  FlagObject(name: "Uganda", countryCode: "UG"),
  FlagObject(name: "Ukraine", countryCode: "UA"),
  FlagObject(name: "United Arab Emirates (the)", countryCode: "AE"),
  FlagObject(
      name: "United Kingdom of Great Britain and Northern Ireland (the)",
      countryCode: "GB"),
  FlagObject(
      name: "United States Minor Outlying Islands (the)", countryCode: "UM"),
  FlagObject(name: "United States of America (the)", countryCode: "US"),
  FlagObject(name: "Uruguay", countryCode: "UY"),
  FlagObject(name: "Uzbekistan", countryCode: "UZ"),
  FlagObject(name: "Vanuatu", countryCode: "VU"),
  FlagObject(name: "Venezuela (Bolivarian Republic of)", countryCode: "VE"),
  FlagObject(name: "Viet Nam", countryCode: "VN"),
  FlagObject(name: "Virgin Islands (British)", countryCode: "VG"),
  FlagObject(name: "Virgin Islands (U.S.)", countryCode: "VI"),
  FlagObject(name: "Wallis and Futuna", countryCode: "WF"),
  FlagObject(name: "Western Sahara", countryCode: "EH"),
  FlagObject(name: "Yemen", countryCode: "YE"),
  FlagObject(name: "Zambia", countryCode: "ZM"),
  FlagObject(name: "Zimbabwe", countryCode: "ZW"),
  FlagObject(name: "Åland Islands", countryCode: "AX"),
];
